#!/usr/bin/env python3

#!/usr/bin/env python3
import os
import re
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


def parse_paf(paf_path, min_len=10000, min_id=0.95):
  """Parses high-confidence alignments from PAF files for dotplot generation."""
  alignments = []
  if not os.path.exists(paf_path):
    print(f"[WARNING] Missing PAF file: {paf_path}")
    return pd.DataFrame()

  with open(paf_path, "r") as f:
    for line in f:
      parts = line.strip().split("\t")
      if len(parts) < 11:
        continue
      q_name, q_len = parts[0], int(parts[1])
      q_start, q_end = int(parts[2]), int(parts[3])
      strand = parts[4]
      t_name, t_len = parts[5], int(parts[6])
      t_start, t_end = int(parts[7]), int(parts[8])
      n_matches, block_len = int(parts[9]), int(parts[10])

      identity = n_matches / block_len if block_len > 0 else 0

      if block_len >= min_len and identity >= min_id:
        alignments.append({
            "q_name": q_name,
            "q_len": q_len,
            "q_start": q_start,
            "q_end": q_end,
            "strand": strand,
            "t_name": t_name,
            "t_len": t_len,
            "t_start": t_start,
            "t_end": t_end,
            "identity": identity,
            "block_len": block_len,
        })
  return pd.DataFrame(alignments)


def plot_dotplot(paf_file, out_png, title="Genome Assembly Dotplot"):
  """Plots Synteny Dotplot using top contigs."""
  df = parse_paf(paf_file)
  if df.empty:
    print(f"[SKIP] No alignments found for dotplot in {paf_file}")
    return

  top_targets = df["t_name"].value_counts().head(15).index
  top_queries = df["q_name"].value_counts().head(15).index

  df_filtered = df[
      df["t_name"].isin(top_targets) & df["q_name"].isin(top_queries)
  ]

  plt.figure(figsize=(10, 10))
  sns.set_theme(style="whitegrid")

  for _, row in df_filtered.iterrows():
    color = "#2b5c8f" if row["strand"] == "+" else "#d95f02"
    plt.plot(
        [row["t_start"] / 1e6, row["t_end"] / 1e6],
        [row["q_start"] / 1e6, row["q_end"] / 1e6],
        color=color,
        linewidth=1.2,
        alpha=0.75,
    )

  plt.title(title, fontsize=14, fontweight="bold", pad=15)
  plt.xlabel("Target Contig Position (Mb)", fontsize=11)
  plt.ylabel("Query Contig Position (Mb)", fontsize=11)

  from matplotlib.lines import Line2D

  legend_elements = [
      Line2D([0], [0], color="#2b5c8f", lw=2, label="Forward (+)"),
      Line2D([0], [0], color="#d95f02", lw=2, label="Inverted (-)"),
  ]
  plt.legend(handles=legend_elements, loc="upper right")

  plt.tight_layout()
  plt.savefig(out_png, dpi=300)
  plt.close()
  print(f"[SUCCESS] Saved Dotplot: {out_png}")


def plot_identity_bins(outdir, prefix, title, out_png):
  """Robustly parses and plots Identity Bins generated by assembly_comparison.sh."""
  file_path = os.path.join(outdir, f"{prefix}.identity_bins.txt")
  if not os.path.exists(file_path):
    print(f"[MISSING] File not found: {file_path}")
    return

  records = []
  with open(file_path, "r") as f:
    for line in f:
      line = line.strip()
      if not line:
        continue
      # Extract bin name and final integer count using regex
      match = re.match(r"^(.+)\s+(\d+)$", line)
      if match:
        bin_label = match.group(1).strip()
        count = int(match.group(2))
        records.append({"Bin": bin_label, "Count": count})

  df = pd.DataFrame(records)
  if df.empty:
    print(f"[SKIP] No valid counts parsed in {file_path}")
    return

  plt.figure(figsize=(8, 5))
  sns.set_theme(style="whitegrid")

  ax = sns.barplot(
      data=df, x="Bin", y="Count", palette="Blues_d", hue="Bin", legend=False
  )

  plt.title(title, fontsize=13, fontweight="bold", pad=12)
  plt.xlabel("Sequence Identity Bin", fontsize=11)
  plt.ylabel("Number of Alignment Blocks", fontsize=11)

  # Annotate counts over the bars
  for p in ax.patches:
    height = p.get_height()
    if not np.isnan(height) and height > 0:
      ax.annotate(
          f"{int(height):,}",
          (p.get_x() + p.get_width() / 2.0, height),
          ha="center",
          va="bottom",
          fontsize=9,
          xytext=(0, 3),
          textcoords="offset points",
      )

  plt.tight_layout()
  plt.savefig(out_png, dpi=300)
  plt.close()
  print(f"[SUCCESS] Saved Identity Bins plot: {out_png}")


# ------------------------------------------------------------------------------
# MAIN EXECUTION
# ------------------------------------------------------------------------------
if __name__ == "__main__":
  out_dir = "assembly_comparison_paf"
  fig_dir = "figures_assembly"
  os.makedirs(fig_dir, exist_ok=True)

  # 1. Synteny Dotplots
  plot_dotplot(
      "male_to_female.paf",
      os.path.join(fig_dir, "male_vs_female_dotplot.png"),
      "Assembly Collinearity: Male Query vs Female Target",
  )

  plot_dotplot(
      "female_to_male.paf",
      os.path.join(fig_dir, "female_vs_male_dotplot.png"),
      "Assembly Collinearity: Female Query vs Male Target",
  )

  # 2. Sequence Identity Breakdown
  plot_identity_bins(
      out_dir,
      "male_vs_female",
      "Male vs Female Alignment Identity Bins",
      os.path.join(fig_dir, "male_vs_female_identity.png"),
  )

  plot_identity_bins(
      out_dir,
      "female_vs_male",
      "Female vs Male Alignment Identity Bins",
      os.path.join(fig_dir, "female_vs_male_identity.png"),
  )